services:
  api:
    build: .
    ports:
      - "8000:80"
      - "8001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=P@sw0rd12345
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
      - ./compose-configuration/appsettings.Development.json:/app/appsettings.Development.json
  ui:
    build: ./src/UI/
    ports:
      - "3000:3000"
    volumes:
      - ./src/UI/node_modules:/app/node_modules
      - ./compose-configuration/.env:/app/.env
    links:
      - api
